Name: Leighton Flanagan

Labpartner(s)

In [12]:
#import statements go here
import numpy as np
import pandas as pd

# Class 9.2

You all will finish presenting your movies from Lab 7.2. 

Today Victoria Garza will give an overview and demo of the LSU HPC system

Reminder your final project proposal is due Monday by 5 PM (note new due date). On Tuesday you will pitch your final project proposal to the class in a short (5 min talk).

# Warmup 9.2

**W.1** Create the following numpy array. Print out the values to check!

[[0. 0. 0. 0. 0. 0. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 5. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 0. 0. 0. 0. 0. 0.]]

In [11]:
zeros = np.zeros((7,7))
zeros[1:6,1:6] = 1
zeros[3,3] = 5
print(zeros)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

**W.2** Pandas filtering and sorting practice with Chipotle data

Import the dataset from this address https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv
Assign it to a variable called chipo.
1. How many products cost more than $10.00?
2. What is the price of each item?
    1. Print a data frame with only two columns item_name and item_price
    2. Sort by the name of the item
1. What was the quantity of the most expensive item ordered?
1. How many times did someone order more than one Canned Soda?

In [28]:
link = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(link, sep='\t')
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

1.

In [29]:
over_10 = 0
for i in chipo.index:
    if float(chipo.iloc[i, 4].strip('$')) >= 10.00:
        over_10 = over_10 + 1
print('There are ' + str(over_10) + ' products that cost more than $10.00')

There are 1130 products that cost more than $10.00

2.

In [55]:
name_price = chipo.loc[:, ("item_name", "item_price")] 
name_price_new_idx = name_price.set_index("item_name")
name_price_new_idx.sort_values("item_name")

                  item_price
item_name
6 Pack Soft Drink    $12.98
6 Pack Soft Drink     $6.49
6 Pack Soft Drink     $6.49
6 Pack Soft Drink     $6.49
6 Pack Soft Drink     $6.49
...                      ...
Veggie Soft Tacos     $8.75
Veggie Soft Tacos     $8.75
Veggie Soft Tacos     $8.49
Veggie Soft Tacos    $11.25
Veggie Soft Tacos     $8.49

[4622 rows x 1 columns]

3.

In [56]:
prices = []
for i in chipo.index:
    chipo = float(chipo.iloc[i, 4].strip('$'))
    prices.append(price)

In [96]:
prices_df = pd.DataFrame(prices)
max_price = prices_df[0].max()
prices_df[prices_df[0] == prices_df[0].max()]

          0
3598  44.25

In [86]:
print(chipo.iloc[0,4])
type(chipo.iloc[0,4])

$2.39

str

In [97]:
chipo.iloc[3598,4]

'$44.25 '

In [119]:
chipo["prices_float"] = prices_df
test = chipo[chipo["prices_float"] == max_price]
quantity_max_price = chipo.iloc[3598, 1]
print("There were " + str(quantity_max_price) + " bought of the item with the highest price, $" + str(max_price))

There were 15 bought of the item with the highest price, $44.25

4.

In [127]:
soda = chipo[chipo["item_name"] == "Canned Soda"]
soda

,order_id,quantity,item_name,choice_description,item_price,prices_float
18,9,2,Canned Soda,[Sprite],$2.18,2.18
28,14,1,Canned Soda,[Dr. Pepper],$1.09,1.09
51,23,2,Canned Soda,[Mountain Dew],$2.18,2.18
53,24,1,Canned Soda,[Sprite],$1.09,1.09
107,47,1,Canned Soda,[Dr. Pepper],$1.09,1.09
...,...,...,...,...,...,...
3897,1562,1,Canned Soda,[Mountain Dew],$1.09,1.09
3926,1575,1,Canned Soda,[Dr. Pepper],$1.09,1.09
3936,1578,1,Canned Soda,[Diet Dr. Pepper],$1.09,1.09
4008,1604,1,Canned Soda,[Diet Coke],$1.09,1.09
4051,1621,1,Canned Soda,[Sprite],$1.09,1.09

In [128]:
multiple_soda = soda[soda["quantity"] > 1]
multiple_soda

,order_id,quantity,item_name,choice_description,item_price,prices_float
18,9,2,Canned Soda,[Sprite],$2.18,2.18
51,23,2,Canned Soda,[Mountain Dew],$2.18,2.18
162,73,2,Canned Soda,[Diet Coke],$2.18,2.18
171,76,2,Canned Soda,[Diet Dr. Pepper],$2.18,2.18
350,150,2,Canned Soda,[Diet Coke],$2.18,2.18
352,151,2,Canned Soda,[Coca Cola],$2.18,2.18
698,287,2,Canned Soda,[Coca Cola],$2.18,2.18
700,288,2,Canned Soda,[Coca Cola],$2.18,2.18
909,376,2,Canned Soda,[Mountain Dew],$2.18,2.18
1091,450,2,Canned Soda,[Dr. Pepper],$2.18,2.18
1092,450,2,Canned Soda,[Coca Cola],$2.18,2.18
1944,787,2,Canned Soda,[Dr. Pepper],$2.18,2.18
2135,859,2,Canned Soda,[Diet Coke],$2.18,2.18
2235,901,4,Canned Soda,[Sprite],$4.36,4.36
2905,1156,2,Canned Soda,[Coca Cola],$2.18,2.18
2906,1156,2,Canned Soda,[Sprite],$2.18,2.18
3152,1258,2,Canned Soda,[Dr. Pepper],$2.18,2.18
3364,1349,2,Canned Soda,[Coca Cola],$2.18,2.18
3592,1440,2,Canned Soda,[Diet Coke],$2.18,2.18
3866,1550,2,Canned Soda,[Mountain Dew],$2.18,2.18

In [141]:
how_many_multiple_soda = 0
for i in multiple_soda.index:
    how_many_multiple_soda = how_many_multiple_soda + 1

In [142]:
print(str(how_many_multiple_soda) + " people bought more than one canned soda")

20 people bought more than one canned soda

##### Lecture 9.2

### Agenda:

- Questions
- Show us your movies
- Intro to LSU HPC

### Questions

# Lab 9.2

**E.0** Complete the previous labs if you are behind.

**E.1** Submit a screenshot of you using a jupyter notebook on the LSU HPC

**E.2** Complete your final project proposal and submit it in Moodle

**E.3** Prepare a 5 min presentation of your project proposal, including a brief introduction, your research plan, the programming methods you are planning to use, your preliminary results/plots, and your timeline for completion. ​You will present this in class next Tuesday. No late talks this time.

A good target length is 1 slide per minute.

Upload your talk here:
https://lsu.box.com/s/5c95w1s2rrwqy839o3ul3oouzi43s4y1

**Notes** Make notes for yourself on progamming tecniques and commands you learned in the this week, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In NCAR there's home, work, and project directory
- home has 100 GB (all backed up on the servers)
- work directory is where data is,but it's not backed up
- scratch directory: if not used in 180 days, will get deleted
Be careful when using the code rm(it causes you to remove something without checking to make sure you wnat to remove it)